### ISSUE TITLE
How to get the video links parsed from a data source

### ISSUE THREAD

**Issue by adetheprince** [nahog/argentina-android-tv#1]
Hi there!
I really liked the way you made this simple and easy to understand, but is it possible to get the video links from a data source? I mean the links saved outside the app in txt,xml or even Json file.
Example I have a Json file with all video links saved on server, and I want to read the links from there.
Please tell us or share with us as I am a noob and I wanted to learn how this works.

**Comment by nahog** [comment]
There are two methods involved in loading the channel list, the first getChannelsFromFile() currenlty gets the channlels.txt file from the local android storage, I recomend that you change that method to download the json for from the server url instead of loading it from the local storage, that method returns an string right now, but you could make it return an object from your json source instead.

The other method to change would be the parseChannels(channelsFileContent, tuner) method, currently is using a custom but very simple format, you should change the implementation of that method to use the data retrieved from your json file instead to create the model entities.
